export const siteConfig = {
  name: 'LLD Mastery',
  url: process.env.NEXT_PUBLIC_SITE_URL ?? 'https://lldmastery.dev',
  description:
    'Master Low Level Design with interactive problems, 22 design patterns, and OOP concepts. Code examples in Python, Java, C++, and TypeScript.',
  keywords: [
    'Low Level Design',
    'LLD',
    'System Design',
    'Design Patterns',
    'Object Oriented Programming',
    'OOP',
    'Interview Preparation',
    'Coding Interview',
    'Software Engineering',
    'SOLID Principles',
    'Singleton Pattern',
    'Factory Pattern',
    'Observer Pattern',
    'Parking Lot Design',
    'LRU Cache',
    'Vending Machine Design',
    'Python',
    'Java',
    'C++',
    'TypeScript',
  ],
  author: 'LLD Mastery',
  twitterHandle: '@lldmastery',
};
